name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Get npm
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Get wasm-pack
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
    - name: Get wasm-opt
      run: npm install binaryen
    - name: Build
      run: make build
    - uses: actions/upload-artifact@v3
      with:
        name: result
        path: pkg/
